[package]
name = "molecule-fuzzer"
version = "0.1.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.molecule-fuzzing]
path = ".."

[[bin]]
name = "data"
path = "fuzz_targets/data.rs"
test = false
doc = false
bench = false
